In [4]:
import pandas as pd

In [5]:
df = pd.read_csv("/Users/JustinHolmes/Desktop/Staple Health/County/Mental Health Data/Concatenated_Data/US_County_All_Data_71719.csv", skiprows = 0, sep = ',', header = 0, dtype = {'FIPS': 'Int32'})
df.head()

,FIPS,State,County,% with SNAP,Percent Margin of Error (±),Life Expectancy,95% CI - Low_x,95% CI - High_x,Life Expectancy (Black),Life Expectancy (Hispanic),...,95% CI - High.18,Z-Score.34,Estimate; Total:,Total Educated,Percent Educated,Violent Crimes,Property Crimes,2014 Population,Violent Crime Rate,Property Crime Rate
0,1001,Alabama,Autauga,12.798077,1.995163,76.3,75.6,77.1,74.6,NaN,...,42,0.11,36757,32236,87.700302,23.0,266.0,54876.0,42.0,485.0
1,1003,Alabama,Baldwin,8.898322,0.972884,78.6,78.2,79.0,75.6,98.0,...,43,0.36,143022,129025,90.213394,93.0,714.0,199189.0,47.0,358.0
2,1005,Alabama,Barbour,25.356281,2.404316,75.8,74.6,76.9,74.2,NaN,...,39,-0.41,18434,13474,73.093197,15.0,119.0,26758.0,56.0,445.0
3,1007,Alabama,Bibb,14.841090,2.856595,73.9,72.6,75.2,72.3,NaN,...,57,1.28,15859,13026,82.136326,13.0,55.0,22541.0,58.0,244.0
4,1009,Alabama,Blount,11.523353,1.589438,74.6,73.8,75.4,NaN,78.6,...,64,2.54,39475,31495,79.784674,3.0,76.0,57521.0,5.0,132.0

In [6]:
df.isna().sum()

FIPS                                       0
State                                      0
County                                     0
% with SNAP                                0
Percent Margin of Error (±)                0
Life Expectancy                           69
95% CI - Low_x                            69
95% CI - High_x                           69
Life Expectancy (Black)                 1803
Life Expectancy (Hispanic)              1895
Life Expectancy (White)                 1416
# Deaths                                  61
Age-Adjusted Mortality                    61
95% CI - Low.1_x                          61
95% CI - High.1_x                         61
Age-Adjusted Mortality (Black)          1789
Age-Adjusted Mortality (Hispanic)       2304
Age-Adjusted Mortality (White)          1561
# Deaths.1                              1222
Child Mortality Rate                    1222
95% CI - Low.2_x                        1222
95% CI - High.2_x                       1222
Child Mortality Rate (Black)            2634
Child Mortality Rate (Hispanic)         2768
Child Mortality Rate (White)            2521
# Deaths.2                              1882
Infant Mortality Rate                   1882
95% CI - Low.3_x                        1882
95% CI - High.3_x                       1882
Infant Mortality Rate (Black)           2792
                                        ...
Z-Score.30                                61
Presence of Drinking Water Violation      43
Z-Score.31                                61
% Severe Housing Problems                  0
95% CI - Low.16_y                          1
95% CI - High.16_y                         1
Severe Housing Cost Burden                 0
Overcrowding                               0
Inadequate Facilities                      0
Z-Score.32                                61
% Drive Alone                              0
95% CI - Low.17                            0
95% CI - High.17                           0
Z-Score.33                                61
% Drive Alone (Black)                   1964
% Drive Alone (Hispanic)                1858
% Drive Alone (White)                   1481
# Workers who Drive Alone                  0
% Long Commute - Drives Alone              0
95% CI - Low.18                            0
95% CI - High.18                           0
Z-Score.34                                61
Estimate; Total:                           0
Total Educated                             0
Percent Educated                           0
Violent Crimes                             8
Property Crimes                            8
2014 Population                            8
Violent Crime Rate                         8
Property Crime Rate                        8
Length: 296, dtype: int64